### ISSUE TITLE
fails if there is not an AMI for a region

### ISSUE THREAD

**Issue by seanorama** [leeatkinson/AWSCloudFormationPreProcessor#1]
I'm using some AMIs which do not exist in every region. I left them out of my template file assuming it wouldn't attempt to fill them for that region. But it still fails and attempts to search that region.

Output below. In this case I get the error for eu-central-1 where the AMI does not exist.

```
$ cfnpp -r us-west-2 ./hdp.cloudformation
CloudFormation Pre-Processor 9.2.1

Retrieved region names
regionNames:
  - eu-central-1
  - sa-east-1
  - ap-northeast-1
  - eu-west-1
  - us-east-1
  - us-west-1
  - us-west-2
  - ap-southeast-2
  - ap-southeast-1

Template paths retrieved


templatePaths:
  - ./hdp.cloudformation

Template loaded
path: ./hdp.cloudformation

Got files
directoryPath: ./hdp.cloudformation.d
filePaths:
  - hdp.cloudformation.d/mappings/centos_6.json

Mapping loaded
path: hdp.cloudformation.d/mappings/centos_6.json

AMI not found
templateName:   hdp.cloudformation
mappingName:    centos_6
regionName:     eu-central-1
amiNamePattern: CentOS
amiOwner:       679593333241
amiId:          null

/usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/request.js:32
          throw err;
                ^
TypeError: Cannot read property 'id' of undefined
    at /usr/local/lib/node_modules/cloudformation-preprocessor/lib/main.js:84:31
    at Response.<anonymous> (/usr/local/lib/node_modules/cloudformation-preprocessor/lib/main.js:56:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/request.js:350:18)
    at Request.callListeners (/usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/cloudformation-preprocessor/node_modules/aws-sdk/lib/request.js:22:9)
```

**Comment by leeatkinson** [comment]
Hi - thanks for reporting. This is now fixed. If a region does not have an AMI, it will not appear. 
Lee
